spring:
  datasource:
    url: jdbc:mysql://localhost:3306/star_shipment_db
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: P@ssw0rd
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

